version: 0.0
os: linux

files:
  - source:  /                                      # 인스턴스에 복사할 디렉토리 경로
    destination: /home/ubuntu/liquor                   # 인스턴스에서 파일이 복사되는 위치
    overwrite: yes                                  # 복사할 위치에 파일이 있는 경우 대체

permissions:            # 권한 설정
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  AfterInstall:
    - location: scripts/stop.sh            # hooks에서 실행할 스크립트 위치
      timeout: 60                          # 스크립트 실행에 허용되는 최대 시간이며, 넘으면 배포 실패로 간주됨
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 60
      runas: ubuntu